name: npm-publish
on:
  push:
    branches:
      - master
      - dev
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set ownership (workaround for actions/runner#2033)
      run: |
        # this is to fix GIT not liking owner of the checkout dir
        chown -R $(id -u):$(id -g) $PWD
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 12.0.0
    - name: Install dependencies
      run: npm install
    - name: Publish if version has been updated
      uses: endel/npm-publish-action@master
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^bump (\\S+)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

